### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Vyrwn** [MahmoudAbdelRahman/GH_CPython#1]
Hi Mahmoud,

first of all, thank you very much for developing this, as it has been a missing component from GH. I just want to ask you about the installation process. Is it a simple copy of the gha into the libraries folder?

The component is visible in my tooldbar, but whenever I try to run any code, the process freezes and Rhino crashes. 

Any advise will be much appreciated.

I have several python tools that run outside Grasshopper that I would like to implement and some of them run using Pandas module. Do you think this is something that will be stable enough in the environment you are building?

Thank you very much,
-Byron

**Comment by jkweon** [comment]
How are you, Mahmoud?

I experienced the same issue. Please let us know how to properly install and run the component. 

Thanks in advance.
Jihoon

**Comment by MahmoudAbdelRahman** [comment]
Hi @Vyrwn . Hi @jkweon , 

Thanks so much for your feedback, 

1. Would you please confirm that you open Rhino as administrator?
2. Also, you have to make sure that Python is installed and running properly on your machine, to do this, open a new command prompt and type `python`. A python shell will open as follows: 
![pythonshell](https://user-images.githubusercontent.com/6969514/28336761-79ae9a94-6c03-11e7-95d4-2aeb1c2e2ce3.JPG)
Then close python by typeing `quit()`
3. Then type `path` in the command prompt to make sure that `C:\python27;` exists. 
![pythonexists](https://user-images.githubusercontent.com/6969514/28336844-bb5bdcc2-6c03-11e7-9403-db643fd4d41e.JPG)

> I have several python tools that run outside Grasshopper that I would like to implement and some of them run using Pandas module. Do you think this is something that will be stable enough in the environment you are building?

Yes I think that it will be stable after getting finished, I'm still developing it to connect the component inputs and outputs to the python IDE.
I have used this plugin to implement a [`numpy`](http://www.numpy.org/), [`scipy`](https://www.scipy.org/), [`PyOpenGL `](http://pyopengl.sourceforge.net/) and [`pygame`](https://www.pygame.org/) modules. it ran well.
![pyinterface](https://user-images.githubusercontent.com/6969514/28337099-c3f65d48-6c04-11e7-9437-1cf3420ac750.jpg)
So, Please, let me know if these steps will help, I have uploaded a[ modified version of the plugin on the repository ](GH_CPython/GH_CPython.gha)

**Comment by jkweon** [comment]
Hi Mahmoud AbdelRahman,

Thanks for your email.

It works fine now. The issue is administrator privilege.
You are right. Rhino must be run as an administrator.

This is an awesome development opening a lot of potentials.

Thanks and congratulation!


Jihoon

**Comment by MahmoudAbdelRahman** [comment]
Hi Jinoon, 
This is great!
Thanks so much.
