### ISSUE TITLE
Copy paste from Notepad++

### ISSUE THREAD

**Issue by Alliages** [MahmoudAbdelRahman/GH_CPython#10]
i've got a small bug when i copy paste from notepad++

![_c__users_g meunier_google drive_github_ecosphere_gh_pymap3d_basic py - notepad _2017-08-07_16-51-18](https://user-images.githubusercontent.com/9363988/29032133-aefe7984-7b90-11e7-980c-cc3c14bdabdc.png)

it's pasted with too many spaces

![gh_cpython_2017-08-07_16-56-56](https://user-images.githubusercontent.com/9363988/29032375-73cab80e-7b91-11e7-9ccc-abca17f5e5d0.png)

and it says "IndentationError: unindent does not match any outer indentation level"
If i delete the spaces from line "x,y,z" and then press enter it's then working

**Comment by MahmoudAbdelRahman** [comment]
Hi @Alliages, 
Thanks so much for the feedback, 
I have solved this problem in the latest update : 
https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.rar

You have to copy the files Gh_CPython as well as FastColoredTextBox.dll into grasshopper libraries folder 
![feedback](https://user-images.githubusercontent.com/6969514/29035052-98c5b196-7b9a-11e7-8c2e-4b1682291a69.JPG)
