### ISSUE TITLE
Request: Python 3 support

### ISSUE THREAD

**Issue by TheodoreGalanos** [MahmoudAbdelRahman/GH_CPython#11]
Hi Mahmoud,

Thanks for the amazing progress! I was wondering if it is possible to add as a future goal Python 3 support. 

This is not that critical since the workflows are still completely fine, but I feel a lot of DL libraries are moving to Python 3 support (only?) slowly.

Kind regards,
Theodore.

**Comment by MahmoudAbdelRahman** [comment]
Hi Theodore, 
This would be  a great idea, 
I think the current version roughly supports Python 3 if it is the only version installed on machine. I haven't tried it yet.
Thanks so much. 
Sincere regards,
Mahmoud Abdelrahman.

**Comment by MahmoudAbdelRahman** [comment]
Hi @TheodoreGalanos,
I have added a new feature, that is, choosing Python interpreter whether : Python27, Python34, Python35 ... and so on. by clicking on the blue line at the bottom of any component. 
![image](https://user-images.githubusercontent.com/6969514/29244139-5b7eebd4-7fb1-11e7-9d4d-43b9f6fdfe67.png)

**Comment by TheodoreGalanos** [comment]
This is amazing Mahmoud, thanks!
