### ISSUE TITLE
Rhino crashes in case block comment is removed from script windows.

### ISSUE THREAD

**Issue by jkweon** [MahmoudAbdelRahman/GH_CPython#12]
How are you, Mahmoud?

From my testing of GH_CPython, Rhino crashed in case block comment part (""" ... """) was removed from script windows. I am not sure if it happens only at my computer.

regards,

Jihoon

**Comment by MahmoudAbdelRahman** [comment]
Hi Jihoon, 
I'm fine thanks , how are you? 
Thanks so much for the feedback , Yes it happens to me as well. I'm working on this right now. 

Regards, 
Mahmoud Abdelrahman.

**Comment by MahmoudAbdelRahman** [comment]
Hi Jihoon, 
I have modified it a little bit, Except for the first input, all other inputs are set optional, but I think it would be better to make them dynamically set. for example: 
* in the description of each input: 
    _input_: optional - the description .... etc.
   _input2: required - the description ... etc. 

![picture1](https://user-images.githubusercontent.com/6969514/29140753-db2d8614-7d4b-11e7-9876-845ed5b77618.png)
