### ISSUE TITLE
In case an input variable is not assigned, the component does not run.

### ISSUE THREAD

**Issue by jkweon** [MahmoudAbdelRahman/GH_CPython#13]
Dear Mahmoud,

Thank you for the updated GH_CPython.

In case an input variable is not assigned, the component does not run. Even though this is not an urgent issue, sometimes we need to test before assigning all input variables. 

regards,

Jihoon

**Comment by MahmoudAbdelRahman** [comment]
Hi Jihoon, 
Thanks so much, I'll modify it and upload the file again. 
Regards, 
Mahmoud Abdelrahman

**Comment by MahmoudAbdelRahman** [comment]
Hi Jihoon, 
Now, this problem has been roughly solved, Except for the first input, I have set all other inputs to be optional. 

**I think it could be dynamically set for example:** 
In the description of the inputs : 
    _input1: required - the description of input 1 is ... etc. 
    _input2: optional - the description of input 2 is ... .etc. 

![picture1](https://user-images.githubusercontent.com/6969514/29141453-9b550316-7d4e-11e7-99c7-f198a0356919.png)

**Comment by jkweon** [comment]
Thank you for the update.
