### ISSUE TITLE
Keyboard shortcut for Test

### ISSUE THREAD

**Issue by dantaeyoung** [MahmoudAbdelRahman/GH_CPython#15]
Feature request: Do you think you could implement the 'F5' keyboard shortcut for testing that's in GHPython already? It's a very helpful feature that can make the editor feel a bit more like a REPL.

Thank you!!

**Comment by MahmoudAbdelRahman** [comment]
Hi @dantaeyoung, 
Thanks so much for your note, 
I have just added this feature now , you can download the updated version [here](https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.zip)

I'm still working on the other issue. 
Thanks so much. 
Regards, 
Mahmoud Abdelrahman

**Comment by dantaeyoung** [comment]
@MahmoudAbdelRahman Thank you so much!! This works perfectly.
