### ISSUE TITLE
Strange error on parameter *input*

### ISSUE THREAD

**Issue by dantaeyoung** [MahmoudAbdelRahman/GH_CPython#17]
Hi @MahmoudAbdelRahman! I'm here with another error. Thanks for being so open to feedback!

I'm trying to receive strings and multi-line strings as inputs, but am getting a curious error. My use-case is to input a multi-line string into GH_CPython and to have it in a variable as a multi-line string, but GH_CPython seems to be doing some internal stuff that affects how things are being processed.

Specifically, I'm working with LispHopper so I can input a string such as `(print "hello")` and everything handled and characters escaped properly and placed in a variable in GH_CPython.

Example below:
![http://imgur.com/OvQaJ0B.jpg](http://imgur.com/OvQaJ0B.jpg)

Thanks!

**Comment by MahmoudAbdelRahman** [comment]
Hi @dantaeyoung , 
Thanks for the feedback , 
[Here you are, ](https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.zip)
![image](https://user-images.githubusercontent.com/6969514/29686254-918a0c5c-8918-11e7-93ad-be3f313d4b53.png)

**Comment by dantaeyoung** [comment]
Wow amazing! This works great - thanks for the quick fix! @MahmoudAbdelRahman
