### ISSUE TITLE
last line: "print __name__"

### ISSUE THREAD

**Issue by Costin-M-Leonte** [MahmoudAbdelRahman/GH_CPython#20]
Hello Mahmoud!
You forgot the paranthesis in the print statement in the last line ;p the Grasshopper ( 02 ? ) module can't be imported.
Outstanding initiative, by the way! Thank you so much! I'll try to catch up with the know-how and maybe help in the near future :D

![image](https://user-images.githubusercontent.com/18078210/30242011-ff8e7f32-9596-11e7-9bf0-25e3c6f1caca.png)

edit: same for line 155:  print "you have to create surface from 4 points"

**Comment by MahmoudAbdelRahman** [comment]
Hello @Costin, 
Thanks so much for the constructive feedback, 
I have modified it and uploaded it [here](https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.zip)
`Grasshopper02` is the modified version of Grasshopper, I'm still working on it , but as it is not ready yet, so I've given it prefix (02), it should include the `RhinoScriptSyntax` main geometry objects. 

I'll be very grateful if you contribute to it. Thanks so much. 

Regards, 
Mahmoud AbdelRahman
