### ISSUE TITLE
c:/GH_CPython on shared/lab environments - not working

### ISSUE THREAD

**Issue by varoudis** [MahmoudAbdelRahman/GH_CPython#26]
Hi,

Do you think you can compile and release a version where the 'temp' interpreter files are not on C: but on a "USER"\Desktop\GH_CPython?

On windows lab servers writing on C: or even having separate 'virtual' folder directly on C is not going to work.
If you change the path to be inside the USERS personal folder it would be amazing.

Thanks

**Comment by MahmoudAbdelRahman** [comment]
Hi @varoudis, 
Great idea! , I may also make it optional to specify the working directory. Thanks a lot. 

Best regards, 
Mahmoud.

**Comment by varoudis** [comment]
@MahmoudAbdelRahman thanks for the quick reply. Without pushing or anything.
Do you have an ETA for this? Im using this for teaching and I want to see if I need to find an alternative solution until then.
Classroom PCs are all on a main roaming server.

Thanks

**Comment by MahmoudAbdelRahman** [comment]
Hi @varoudis, 
Yes, I think it is easy and straight forward, I'll set the path to the desktop rather than `C:\GH_CPython\`: 
`path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);`

**Comment by MahmoudAbdelRahman** [comment]
Thanks so much Tasos, 
Would you please try this one ? It works fine with me and it writes to the desktop now. 

[GH_CPython.zip](https://github.com/MahmoudAbdelRahman/GH_CPython/files/1638788/GH_CPython.zip)

Best regards, 
Mahmoud AbdelRahman

**Comment by varoudis** [comment]
thanks!! this works on shared windows server environments.
Just tested it
