### ISSUE TITLE
GH_CPython does not save codes.

### ISSUE THREAD

**Issue by jkweon** [MahmoudAbdelRahman/GH_CPython#3]
Dear Mahmoud,

GH_CPython does not save codes. I know you already fixed bugs in the input parts. Bugs in saving codes also need your care.

Thanks.
Jihoon

**Comment by MahmoudAbdelRahman** [comment]
Thanks so much Jihoon for your feedback, 
Yes, you are right, I'm working on this right now.

**Comment by MahmoudAbdelRahman** [comment]
Finally, I've solved this problem, 
Thanks so much Jihoon for your useful feedback. 
![firstplugin](https://user-images.githubusercontent.com/6969514/28814200-f18c117e-769c-11e7-80e7-6623d794e757.JPG)

**Comment by jkweon** [comment]
Thank you for the update. It works now. This will be powerful contribution to everybody using Python and Rhino.

GH_CPython saves scripts and makes output as a string.  If my understanding is correct, sting output seems to be the current phase of your intention. 

I guess you are also interested in taking care of Rhinocommon geometries such as point, line, curve, mesh, and brep surface. I hope to see the next step soon. 

Thank you very much, Mahmoud.

**Comment by MahmoudAbdelRahman** [comment]
Thanks so much Jihoon, 
Yes, you are right, I'll be working on RhinoCommon in the upcoming updates. 
Sincere regards. 
Mahmoud abdlelrahman
