### ISSUE TITLE
Difference with ghpythonremote

### ISSUE THREAD

**Issue by cadop** [MahmoudAbdelRahman/GH_CPython#38]
Is there any information on the difference with https://github.com/Digital-Structures/ghpythonremote ? Could this comparison be added to the wiki?

**Comment by protactinium91** [comment]
First thing: GHPython Remote Requires a Python 2.7 installation, not compatible with Python 3 while GH_CPYTHON runs on Python 3

**Comment by MahmoudAbdelRahman** [comment]
Thank you @cadop,
Great suggestion.  
I'll add the comparison in the wiki later. I'll also devote some time to push the plugin further. 

Regards.
