### ISSUE TITLE
New inputs are named c instead of z

### ISSUE THREAD

**Issue by mostaphaRoudsari** [MahmoudAbdelRahman/GH_CPython#4]
This is not a bug but is more of an enhancement.

![image](https://user-images.githubusercontent.com/2915573/28647014-a61680ee-7232-11e7-96ef-492b34e766fc.png)

When I add a new input I expect it follows the x, y, z order but it names the new input as c.

**Comment by MahmoudAbdelRahman** [comment]
Hi @mostaphaRoudsari, 
Thanks so much, I'm very pleased to receive your feedback, 
I have solved this problem and changed the first _input name and output_ name and now they follow the normal order x, y, z .. 
![xyzinsteedofxyd](https://user-images.githubusercontent.com/6969514/28651657-681be15c-7283-11e7-8c40-35892a7c0242.JPG)
![gowentgone](https://user-images.githubusercontent.com/6969514/28651701-a1bba532-7283-11e7-8973-6b0c7c219572.JPG)

**Comment by mostaphaRoudsari** [comment]
Perfect! Thanks.
