### ISSUE TITLE
Input access type

### ISSUE THREAD

**Issue by mostaphaRoudsari** [MahmoudAbdelRahman/GH_CPython#5]
Currently the input access is set to list and doesn't seem to be possible to change it.

**Comment by MahmoudAbdelRahman** [comment]
Thanks so much @mostaphaRoudsari for your feedback,

I have solved this problem, now it is able to handle item dataAccess in addition to list dataAccess. 
I'm now working on linking the output, in addition to text highlighting, saving data and I'll pay more attention to merging IronPython with Cpython following your note. 
Thanks so much.
![datatypes](https://user-images.githubusercontent.com/6969514/28651806-540d2a80-7284-11e7-888f-3519ff58abcd.JPG)

**Comment by mostaphaRoudsari** [comment]
Hi @MahmoudAbdelRahman, Great! I used the GHA component from the root folder. Where can I update the latest GHA file?

Also handling both IronPython and CPython in the same component is not really critical. I think it would be easier if you concentrate on one and get it fully to work before introducing a new problem.

I'm closing this issue as it has been addressed already.

**Comment by MahmoudAbdelRahman** [comment]
Hi @mostaphaRoudsari, 
Thanks so much. Yes, I upload the updated GHA files to the [root folder](https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.gha), and [.\bin\ folder](https://github.com/MahmoudAbdelRahman/GH_CPython/tree/master/GH_CPython/GH_CPython/bin) as well. I agree with you, I'll concentrate on finishing this component at first.
Thanks so much.
