### ISSUE TITLE
input parameter and editing window issue

### ISSUE THREAD

**Issue by jkweon** [MahmoudAbdelRahman/GH_CPython#7]
Dear Mahmoud,

Adding input parameter such as 'x' without assigning data to it makes me unable to open the editing window of GH_CPython. I am not sure if it is a kind of bug or another issue.

Best regards,

Jihoon

**Comment by MahmoudAbdelRahman** [comment]
Hi Jihoon, 
Yes, You are right, 
I've solved the problem, would you test it ? 
https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.gha

Thanks so much.
