### ISSUE TITLE
New feature : Line number

### ISSUE THREAD

**Issue by Alliages** [MahmoudAbdelRahman/GH_CPython#9]
Really great job !
I think it would be good if we had line numbering.

**Comment by MahmoudAbdelRahman** [comment]
Thanks so much Alliages for your feedback, 
I have just added this feature now, you can download it from this link: 
https://github.com/MahmoudAbdelRahman/GH_CPython/blob/master/GH_CPython.rar
Then copy Gh_CPython and FastColoredTextBox.dll into the plugins folder e.g (C:\Users\gamma\AppData\Roaming\Grasshopper\Libraries)

**I'm working on the syntax highlight now.**

![feedback](https://user-images.githubusercontent.com/6969514/29034867-fff7dd36-7b99-11e7-958c-9980f4fe8dc0.JPG)
